### PR TITLE
Prefer gums-host-cron for generating user-vo-map file (SOFTWARE-2482)

### PR DESCRIPTION
**Pull request by matyasselmeci**
:(

### CODE REVIEW

**Comment by bbockelm** [comment]
Why?  Doesn't seem to explain the decision in the commit message or the referenced ticket...

**Comment by matyasselmeci** [comment]
Right now gums-json does not filter out VOs mapped to nonexistant users from user-vo-map, leading to a much larger user-vo-map file than what gums-host-cron generates. This leads to a longer allowed_vos list than what we get by using gums-host-cron.

**Comment by bbockelm** [comment]
Gotcha.  Is there a separate ticket open for that (or are we doing it as part of the larger work?)?

**Comment by matyasselmeci** [comment]
Just made one: https://jira.opensciencegrid.org/browse/SOFTWARE-2804

**Pull request merged**
